config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "/language/:locale", to: "users#language", as: :change_locale
  get "register", to: "users#register"
  get "login", to: "users#login"
  post "sign_up", to: "users#sign_up"
  delete "logout", to: "users#logout"

  post "/graphql", to: "graphql#execute"

  # 搜索和通知
  get "/search" => "search#index", :as => "search"
  get "notifications/index" => "notifications#index"
  delete "notifications/clean" => "notifications#clean"

  resources :users do
    member do
      patch :change_password
      get :articles
      get :comments
      get :favorites
      get :followers
      get :following
      post :follow
      post :unfollow
    end
  end

  get "articles/node:id" => "articles#node", :as => "node_articles"
  resources :articles do
    member do
      post :like
      delete :destroy_like
      post :favorite
      delete :destroy_favorite
    end
    collection do
      get :no_comment
      get :popular
    end
    resources :comments do
      post :like
      delete :destroy_like
    end
  end

  resources :chats

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  # 管理员后台
  namespace :admin do
    # sidekiq后台
    require "sidekiq/web"
    require "sidekiq-status/web"
    require "sidekiq/grouping/web"
    require "sidekiq-scheduler/web"
    mount Sidekiq::Web => "/sidekiq"

    root to: "home#index", as: "root"
    resources :sections
    resources :nodes
    get "foods/new_simple", to: "foods#new_simple"
    resources :foods
    get "practices/bootstrap_table" => "practices#bootstrap_table"
    get "practices/get_data" => "practices#get_data"
    resources :articles
  end

  mount ActionCable.server => "/cable"
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Elasticsearch::Model
  include Searchable
  include Wisper::Publisher

  belongs_to :user
  belongs_to :node
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments, allow_destroy: true

  paginates_per 20

  validates_presence_of :title, :body, :node_id

  scope :popular, -> { order(likes_count: :desc) }
  scope :no_comment, -> { where(comment_count: 0).order(created_at: :desc) }
  scope :time_desc, -> { order(created_at: :desc) }

  def liked_by_user?(user)
    return false if user.blank?
    liked_user_ids.include?(user.id)
  end

  # 创建之后创建提醒信息
  after_commit :create_reply_notify, on: :create

  # Test of RabbitMq
  def publish_article
    Publisher.publish("Articles", attributes)
  end

  def create_reply_notify
    NotifyArticleWorker.perform_async(id)
    publish(:article_create, self)
  end

  def self.notify_article_created(article_id)
    article = Article.find_by_id(article_id)
    return unless article && article&.user

    follower_ids = article.user.follower_ids.uniq
    return if follower_ids.empty?

    notified_user_ids = article.mentioned_user_ids

    # 给关注者发通知
    default_note = {notify_type: "article", target_type: "Article", target_id: article.id, actor_id: article.user_id}
    Notification.bulk_insert do |worker|
      follower_ids.each do |uid|
        # 排除同一个回复过程中已经提醒过的人
        next if notified_user_ids.include?(uid)
        # 排除回帖人
        next if uid == article.user_id
        note = default_note.merge(user_id: uid)
        worker.add(note)
      end
    end

    Notification.bulk_insert(set_size: 100) do |worker|
      notified_user_ids.each do |user_id|
        note = {
          notify_type: "mention",
          actor_id: article.user_id,
          user_id: user_id,
          target_type: self.class.name,
          target_id: id
        }
        worker.add(note)
      end
    end

    true
  end

  def update_last_reply(comment)
    return false if comment.blank?
    self.comment_count = comments.count
    save
  end

  index_name "personal"
  document_type "articles"

  mapping do
    indexes :title, term_vector: :yes
    indexes :body, term_vector: :yes
  end

  def as_indexed_json(options = {})
    as_json(only: ["title", "body"])
  end
end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true

module Admin
  class ArticlesController < Admin::ApplicationController
    def index
      @articles = Article.page(params[:page])
    end

    def new
      @article = Article.new
    end

    def create
      permit_params
      @article = Article.new(permit_params)
      @article.user_id = current_user.id
      @article.comments.map { |m| m.user_id = current_user.id }
      if @article.save
        redirect_to admin_articles_path, notice: "article was successfully created."
      else
        render :new_admin_article
      end
    end

    def update
    end

    private

    def permit_params
      params.require(:article).permit(:node_id, :title, :body, comments_attributes: [:user_id, :body, :_destroy])
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update like destroy_like destroy]

  def index
    @articles = Article.time_desc.includes(:user, :node).page(params[:page])
  end

  def new
    @article = Article.new(user_id: current_user.id)
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    full_name = @article.body.scan(/@([A-Za-z0-9\-_.]{3,20})/).flatten.map(&:downcase)
    if full_name.any?
      @article.mentioned_user_ids = User.where("lower(full_name) IN (?) AND id != (?)", full_name, @article.user_id).limit(5).pluck(:id)
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
      else
        format.html { render action: "new" }
      end
    end
  end

  def show
    @comments = @article.comments

    check_current_user_status_for_article

    fresh_when([@comments, @article])
  end

  def edit
  end

  def update
    authorize @article

    @article.update_attributes(article_params)
    if @article.save
      redirect_to(article_path(@article.id), notice: "更新文章成功")
    else
      render action: "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to(articles_path, notice: "文章成功删除")
  end

  %w[no_comment popular].each do |name|
    define_method(name) do
      @articles = Article.send(name.to_sym).includes(:user)
      @articles = @articles.page(params[:page])

      render action: "index"
    end
  end

  def like
    @article.liked_user_ids << current_user.id
    @article.likes_count = @article.liked_user_ids.length
    @article.save
    render plain: @article.likes_count
  end

  def destroy_like
    @article.liked_user_ids.delete(current_user.id)
    @article.likes_count = @article.liked_user_ids.length
    @article.save
    render plain: @article.likes_count
  end

  def favorite
    current_user.favorite_article(params[:id])
    render plain: "1"
  end

  def destroy_favorite
    current_user.unfavorite_article(params[:id])
    render plain: "1"
  end

  def node
    @node = Node.find(params[:id])
    @articles = @node.articles
    @articles = @articles.includes(:user).time_desc.page(params[:page])
    render action: "index"
  end

  private

  def article_params
    params.require(:article).permit!
  end

  def set_article
    @article ||= Article.find(params[:id])
  end

  def check_current_user_status_for_article
    return false unless current_user

    # 通知处理
    current_user.read_article(@article, comment_ids: @comments.collect(&:id))
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
  # 文章赞
  def like_able_tag(article)
    label = "#{article.likes_count} 个赞"
    title, state, icon_name =
      if article.liked_by_user?(current_user)
        %w[取消赞 active heart]
      else
        ["赞", "", "heart-o"]
      end

    icon = content_tag("i", "", class: "fa fa-#{icon_name}")
    like_label = raw "#{icon} <span>#{label}</span>"

    link_to(like_label, "#", :title => title, "data-count" => article.likes_count,
                             "data-state" => state, "data-type" => article.class, "data-id" => article.id,
                             :class => "likeable #{state}")
  end

  # 文章收藏
  def article_favorite_tag(article)
    link_title = "收藏"
    class_name = "btn btn-default"
    if current_user.favorite_article_ids.include?(article.id)
      class_name = "active btn btn-default"
      link_title = "取消收藏"
    end

    icon = raw(content_tag("i", "", class: "fa fa-bookmark"))

    link_to(raw("#{icon} 收藏"), "#", :title => link_title, :class => "bookmark #{class_name}", "data-id" => article.id)
  end

  # 文章链接
  def article_title_tag(article, opts = {})
    return "文章已经被删除" if article.blank?
    path = article_path(article)
    link_to(article.title, path, title: article.title)
  end
end

app/views/articles/_article.html.erb
<% cache(['article',article]) do %>
<div class="topic media">
  <div class="media-left">
    <%= user_avatar_tag(article.user, :avatar) %>
  </div>
  <div class="infos media-body">
    <div class="title media-heading">
      <%= link_to article.title, article_path(article) %>
    </div>
    <div class="info">
      <%= render_node_name(article.node.name, article.node.id) %>
      <span class="hidden-mobile">
        •
        <%= user_name_tag(article.user) %>
        •
        <%= time_ago_now(article.created_at) %>
      </span>
    </div>
  </div>
  <div class="count media-right">
    <%= link_to(article.comment_count, class: 'state-false') %>
  </div>
</div>
<% end %>

app/views/articles/_article_info.html.erb
<div class="panel-heading media clearfix">
  <div class="media-body">
    <h3 class="media-heading"><%= @article.title %></h3>

    <div class="info">
      <div class="info small">
        <%= render_node_name(@article.node.name, @article.node.id) %>
        •
        <%= user_name_tag(@article.user) %>
        •
        <%= time_ago_now(@article.created_at) %>
      </div>
    </div>
  </div>
  <div class="media-right">
    <%= user_avatar_tag(@article.user, :avatar) %>
  </div>
</div>

app/views/articles/_article_sidebar.html.erb
<div id="article-sidebar" data-spy="affix">
  <div class="panel panel-default">
    <div class="panel-body">
      <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>

      <div class="buttons">
        <div class="group likes opts">
          <%= like_able_tag(@article) %>
        </div>
        <div class="group">
          <div class="btn-group" role="group">
            <% if current_user %>
                <%= article_favorite_tag(@article) %>
            <% end %>
          </div>
        </div>
      </div>

      <hr/>
      <div class="group">
        <%= social_share_button_tag (@article.title) %>
      </div>
      <hr/>
      <div class="reply-buttons">
        <div class="total">
          共收到 <b><%= @article.comments.count %></b> 条回复
        </div>
        <a href="#reply" class="btn btn-success btn-block btn-focus-reply">参与回复</a>
      </div>
      <hr/>
      <div class="group opts">
        <% if owner?(@article) %>
            <%= link_to "", edit_article_path(@article), class: 'fa fa-pencil', title: '修改本帖' %>
            <%= link_to "", @article, method: :delete, 'data-confirm' => '确认删除', class: 'fa fa-trash', title: '删除本帖' %>
        <% end %>
      </div>
      <a href="#" class="btn btn-block btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
    </div>
  </div>

</div>

<script>
    //移动到页面的底部
    $('.btn-move-page').click(function (e) {
        var moveType, opts, target;
        target = $(e.currentTarget);
        moveType = target.data('type');
        opts = {
            scrollTop: 0
        };
        if (moveType === 'bottom') {
            opts.scrollTop = $('body').height();
        }
        $("body, html").animate(opts, 300);
        return false;
    });

    $('a.likeable').click(function () {
        if (!App.current_user_id) {
            location.href = "/login"
        }
        var article_id, likes_count;
        article_id = $(this).data("id");
        likes_count = parseInt($(this).data("count"));
        if ($(this).data("state") !== "active") {
            $.ajax({
                url: "/articles/" + article_id + "/like",
                type: "POST",
                data: {
                    id: article_id
                }
            });
            likes_count += 1;
            $(this).data('count', likes_count);
            $(this).data('state', 'active')
            $(this).attr('class', 'likeable active')
            $("i.fa", $(this)).attr("class", "fa fa-heart");
            $('span', $(this)).text(likes_count + " 个赞")
        } else {
            $.ajax({
                url: "/articles/" + article_id + '/destroy_like',
                type: "DELETE"
            });

            likes_count -= 1;
            $(this).data('count', likes_count);
            $(this).data('state', '')
            $(this).attr('class', 'likeable')
            $("i.fa", $(this)).attr("class", "fa fa-heart-o");
            $('span', $(this)).text(likes_count + " 个赞")
        }
        return false;

    });

    $('a.bookmark').click(function () {
        var link, article_id;
        article_id = $(this).data("id");
        link = $(".bookmark[data-id='" + article_id + "']");
        if (link.hasClass("active")) {
            $.ajax({
                url: "/articles/" + article_id + "/destroy_favorite",
                type: "DELETE"
            });
            link.attr("title", "收藏").removeClass("active");
        } else {
            $.post("/articles/" + article_id + "/favorite");
            link.attr("title", "取消收藏").addClass("active");
        }
        return false;
    })

</script>

app/views/articles/_comment_form.html.erb
<%
   user_ids = current_user.follower_ids + current_user.following_ids
   users = User.where(:id => user_ids).collect { |i| i.full_name }.to_s.html_safe
%>
<%= form_for(Comment.new, remote: true, url: article_comments_url(@article)) do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: 'article-editor form-control', rows: '4', tabindex: '1' %>
  </div>
  <div class="submit-buttons">
    <button type="submit" id="reply-button" class="btn btn-primary" tabindex="2">提交回复</button>
    <span class="help-inline" style="padding-left: 5px;" title="或者 Ctrl + Enter"><kbd>Command</kbd> + <kbd>Enter</kbd></span>

    <div class="pull-right"><a href="/markdown" target="_blank">排版说明</a></div>
  </div>
<% end %>

<script>
  //ctrl + enter 提交
  $("textarea.article-editor").keydown(function (e) {
    if ((e.ctrlKey || e.metaKey) && e.keyCode == 13) {
      $("form#new_comment").submit()
    }
  });
  //@用户
  data = <%= users %>;
  $('textarea.article-editor').atwho({at: "@", 'data': data});
</script>

app/views/articles/_index_sections.html.erb
<div class="row node-list">
  <% Section.includes(:nodes).all.each do |section| %>
    <div class="node media">
      <label class="media-left"><%= section.name %></label>
            <span class="nodes media-body">
              <% section.nodes.each do |node| %>
                <span class="name"><%= link_to(node.name, '#', title: node.name, data: {id: node.id}) %></span>
              <% end %>
            </span>
    </div>
  <% end %>
</div>

app/views/articles/_node_info.html.erb
<% if !node.blank? %>
  <div class="node-info">
    <div class="name">
      <strong><%= node.name %></strong> <span class="total">共有 <%= node.articles.count %> 个讨论主题</span>
    </div>
    <div class="summary">
      <%= node.summary %>
    </div>
  </div>
<% else %>
  <div class="filter pull-right">
    <span class="l">查看:</span>
    <a data-turbolinks-action="replace" href="<%= articles_path %>"<%= " class=active" if action_name == "index" %>>默认</a>
    •
    <a data-turbolinks-action="replace" href="<%= popular_articles_path %>" class="popular<%= " active" if action_name == "popular" %>">优质帖子</a>
    •
    <a data-turbolinks-action="replace" href="<%= no_comment_articles_path %>" <%= " class=active" if action_name == "no_reply" %>>无人问津</a>
  </div>
<% end %>

app/views/articles/_node_selector.html.erb
<div class="modal" id="node-selector" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <strong>选择话题节点</strong>
      </div>
      <div class="modal-body">
        <%= render 'articles/index_sections' %>
      </div>
    </div>
  </div>
</div>
<script>

  $("#node-selector .nodes .name a").click(function () {
    $("#node-selector").modal('hide')
    var node_id = $(this).data('id')
    var node_name = $(this).text()
    $('.form input[name="article[node_id]"]').val(node_id)
    $('#node-selector-button').html(node_name)
  });

</script>

app/views/articles/_sidebar_box_tips.html.erb
<div class="panel panel-default">
  <div class="panel-heading">小帖士</div>
  <div class="panel-body">
    <%= random_tips %>
  </div>
</div>

app/views/articles/_sidebar_for_article_index.html.erb
<div class="panel panel-default clearfix">
  <div class="panel-body">
    <div class="btn-group btn-block pull-left">
      <%= link_to('发布新话题', new_article_path, class: 'btn btn-primary') %>
    </div>
  </div>
</div>

<%= render 'articles/sidebar_box_tips' %>
<% cache(['sidebar_statistics', Time.now.strftime("%Y-%m-%d %H")]) do %>
  <div class="panel panel-default">
    <div class="panel-heading">统计信息</div>
    <ul class="list-group">
      <li class="list-group-item">社区会员: <%= User.unscoped.count %> 人</li>
      <li class="list-group-item">帖子数: <%= Article.unscoped.count %> 个</li>
      <li class="list-group-item">回帖数: <%= Comment.unscoped.count %> 条</li>
    </ul>
  </div>
<% end %>

app/views/articles/edit.html.erb
<section class="content">
  <%= render 'node_selector' %>
  <div class="box box-default">
    <div class="box-header with-border">
      <h3 class="box-title">编辑文章</h3>
      <%= render 'shared/box_tools' %>
    </div>

    <div class="box-body">
      <!--错误信息-->
      <%= render 'shared/error_messages', target: @article %>

      <%= form_for @article, html: { class: 'form' } do |f| %>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-btn">
              <button type="button" class="btn btn-default" id="node-selector-button"
                      data-toggle="modal" data-target="#node-selector"><%= @article.node.try(:name) || '选择节点...' %></button>
            </div>
            <%= f.hidden_field :node_id %>
            <%= f.text_field :title, class: "form-control", placeholder: "在这里填写标题" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="nav-tabs-custom">
              <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_1" data-toggle="tab">编辑</a></li>
                <li><a href="#tab_2" data-toggle="tab">预览</a></li>
                <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
              </ul>

              <div class="tab-content">
                <div class="tab-pane active" id="tab_1">
                  <div class="form-group">
                    <%= f.text_area :body, class: "topic-editor form-control closewarning", rows: 20 %>
                  </div>
                </div>

                <div class="tab-pane" id="tab_2" style="height: 414px">
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit t('helpers.submit.submit'), class: "btn btn-primary col-xs-2" %>
        </div>
      <% end %>

    </div>
  </div>
</section>

app/views/articles/new.html.erb
<%= render 'node_selector' %>
<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">发布新文章</h3>
    <%= render 'shared/box_tools' %>
  </div>

  <div class="box-body">
    <!--错误信息-->
    <%= render 'shared/error_messages', target: @article %>

    <%= form_for @article, html: {class: "form"} do |f| %>
      <div class="form-group">
        <div class="input-group">
          <div class="input-group-btn">
            <button type="button" class="btn btn-default" id="node-selector-button"
                    data-toggle="modal" data-target="#node-selector"><%= '选择节点...' %></button>
          </div>
          <%= f.hidden_field :node_id %>
          <%= f.text_field :title, class: "form-control", placeholder: "在这里填写标题" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab_1" data-toggle="tab">编辑</a></li>
              <li><a href="#tab_2" data-toggle="tab">预览</a></li>
              <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
            </ul>

            <div class="tab-content">
              <div class="tab-pane active" id="tab_1">
                <div class="form-group">
                  <%= f.text_area :body, class: "topic-editor form-control closewarning", rows: 20 %>
                </div>
              </div>

              <div class="tab-pane" id="tab_2" style="height: 414px">
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit t('helpers.submit.submit'), class: "btn btn-primary col-xs-2" %>
      </div>
    <% end %>

  </div>
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="topic-detail panel panel-default">
      <%= render partial: 'article_info', locals: {:@article => @article} %>
      <div class="panel-body markdown">
        <article>
          <%= markdown @article.body %>
        </article>
      </div>
    </div>

    <div id="replies" class="panel panel-default" data-last-floor="<%#= @replies.count(:all) %>">
      <div class="total panel-heading">
        共收到 <b><%= @article.comments.count %></b> 条回复
      </div>
      <div class="items panel-body">
        <% cache([@article]) do %>
          <%= render partial: '/comments/comment', collection: @comments %>
        <% end %>
      </div>
    </div>

    <div id="reply" class="panel panel-default">
      <div class="panel-heading">回帖</div>
      <div class="panel-body">
        <% if current_user %>
        <%= render 'comment_form' %>
            <% end %>
      </div>
    </div>

  </div>

  <div class="article-sidebar col-md-3">
    <%= render 'article_sidebar' %>
  </div>
</div>

<script>
  //评论喜欢
  $('a.comment_like').click(function () {
    var comment_id, likes_count;
    comment_id = $(this).data("id");
    likes_count = parseInt($(this).data("count"));
    if ($(this).data("state") !== "active") {
      $.ajax({
        url: "/articles/" + "<%= @article.id %>" + "/comments/" + comment_id + "/like",
        type: "POST",
        data: {
          id: comment_id
        }
      });
      likes_count += 1;
      $(this).data('count', likes_count);
      $(this).data('state', 'active')
      $(this).attr('class', 'comment_like active')
      $("i.fa", $(this)).attr("class", "fa fa-heart");
      $('span', $(this)).text(likes_count + " 个赞")
    } else {
      $.ajax({
        url: "/articles/" + "<%= @article.id %>" + "/comments/" + comment_id + "/destroy_like",
        type: "DELETE",
        data: {
          id: comment_id
        }
      });

      likes_count -= 1;
      $(this).data('count', likes_count);
      $(this).data('state', '')
      $(this).attr('class', 'comment_like')
      $("i.fa", $(this)).attr("class", "fa fa-heart-o");
      $('span', $(this)).text(likes_count + " 个赞")
    }
    return false;
  });

  //回复此楼
  $(".btn-reply").click(function () {
    var comment, floor, comment_body, full_name, new_text
    comment = $(this)
    floor = comment.data("floor")
    full_name = comment.data("login")
    comment_body = $("#comment_body")
    new_text = "#" + floor + "楼" + "@" + full_name + " "
    if (comment_body.val().trim().length == 0) {
      new_text += ''
    }
    else {
      new_text = "\n" + new_text
    }
    comment_body.focus().val(comment_body.val() + new_text);
  });

  //控制权限显示
  $(document).ready(function () {
    <% if admin? %>
    $("#replies .reply a.edit").css('display', 'inline-block');
    <% elsif current_user %>
    $("#replies .reply a.edit[data-uid='<%= current_user.id %>']").css('display', 'inline-block');
    <% end %>
  })
</script>