config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "/language/:locale", to: "users#language", as: :change_locale
  get "register", to: "users#register"
  get "login", to: "users#login"
  post "sign_up", to: "users#sign_up"
  delete "logout", to: "users#logout"

  post "/graphql", to: "graphql#execute"

  # 搜索和通知
  get "/search" => "search#index", :as => "search"
  get "notifications/index" => "notifications#index"
  delete "notifications/clean" => "notifications#clean"

  resources :users do
    member do
      patch :change_password
      get :articles
      get :comments
      get :favorites
      get :followers
      get :following
      post :follow
      post :unfollow
    end
  end

  get "articles/node:id" => "articles#node", :as => "node_articles"
  resources :articles do
    member do
      post :like
      delete :destroy_like
      post :favorite
      delete :destroy_favorite
    end
    collection do
      get :no_comment
      get :popular
    end
    resources :comments do
      post :like
      delete :destroy_like
    end
  end

  resources :chats

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  # 管理员后台
  namespace :admin do
    # sidekiq后台
    require "sidekiq/web"
    require "sidekiq-status/web"
    require "sidekiq/grouping/web"
    require "sidekiq-scheduler/web"
    mount Sidekiq::Web => "/sidekiq"

    root to: "home#index", as: "root"
    resources :sections
    resources :nodes
    get "foods/new_simple", to: "foods#new_simple"
    resources :foods
    get "practices/bootstrap_table" => "practices#bootstrap_table"
    get "practices/get_data" => "practices#get_data"
    resources :articles
  end

  mount ActionCable.server => "/cable"
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  scope :unread_count, ->(user) { where(user_id: user.id) }

  def self.notify_follow(user_id, follower_id)
    opts = {
      notify_type: "follow",
      user_id: user_id,
      actor_id: follower_id
    }
    return if Notification.where(opts).count > 0
    Notification.bulk_insert do |worker|
      worker.add(opts)
    end
    # Notification.create opts
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications.order("created_at desc").page(params[:page]).per(20)
    @notification_groups = @notifications.group_by { |note| note.created_at.to_date }
  end

  def clean
    Notification.where(user_id: current_user.id).delete_all
    redirect_to "/notifications/index"
  end
end

app/views/notifications/_article.html.erb
<%
   article = Article.find(notification.target_id)
%>
<div class="media-heading">
  创建了帖子 <%= article_title_tag(article) %>
</div>

app/views/notifications/_article_comment.html.erb
<%
   article = Article.find(notification.second_target_id)
   comment = Comment.find(notification.target_id)
%>

<div class="media-heading">
  在帖子
  <%= article_title_tag(article) %> 回复了：
</div>
<div class="media-content summary markdown">
  <%= markdown comment.body %>
</div>

app/views/notifications/_follow.erb
<% user = User.find(notification.actor_id) %>
<% if user.blank? %>
  相关信息已删除
<% else %>
  <div class="media-heading">
    <%= user_name_tag(user) %> 开始关注你了。
  </div>
<% end %>

app/views/notifications/_mention.html.erb
<%
   case notification.target_type
     when 'Comment'
%>
  <%
     comment = Comment.find(notification.target_id)
     article = Article.find(notification.second_target_id) || comment.article
  %>
  <div class="media-heading">
    <span class="info">在 <%= article_title_tag(article) %> 提及你：</span>
  </div>
  <% if comment.present? %>
    <div class="media-content summary markdown">
      <%= markdown comment.body %>
    </div>
  <% end %>
<% when 'Article' %>
  <%
     article = Article.find(notification.target_id)
  %>

  <% if article.blank? %>
    <div class="media-body">相关信息已删除</div>
  <% else %>
    <div class="media-heading">
      在 <%= article_title_tag(article) %> 提及你：
    </div>
    <div class="media-content summary markdown">
      <%= markdown article.body %>
    </div>
  <% end %>
<% end %>

app/views/notifications/_notification.html.erb
<div id="notification-<%= notification.id %>"
     data-id="<%= notification.id %>"
     class="media notification notification-<%= notification.notify_type %>">
  <div class="media-left">
    <%= link_to image_tag(User.find(notification.actor_id).avatar.url), user_path(notification.actor_id), title: User.find(notification.actor_id).full_name, class: 'user-avatar' %>
  </div>
  <div class="media-body">
    <%= render partial: "#{notification.notify_type}", locals: {notification: notification} %>
  </div>
  <div class="media-right">
    <%= notification.created_at.to_formatted_s(:time) %>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="notifications panel">
  <div class="panel-heading hide-ios clearfix">
    所有通知
    <span class="pull-right">
      <%= link_to '清空', notifications_clean_path, class: 'btn btn-sm btn-danger', id: 'btn-remove-all', method: 'delete' %>
    </span>
  </div>
  <div class="panel-body list item-list">
    <% if @notifications.blank? %>
      <div class="notification-group">
        <div class="no-records">没有通知</div>
      </div>
    <% else %>
      <% @notification_groups.each do |group, notifications| %>
        <div class="notification-group">
          <div class="group-title"><i class="fa fa-clock-o"></i> <%= group %></div>
          <%= render notifications %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="panel-footer hide-ios">
    <%= paginate @notifications, :theme => 'bootstrap3' %>
  </div>
</div>