config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "/language/:locale", to: "users#language", as: :change_locale
  get "register", to: "users#register"
  get "login", to: "users#login"
  post "sign_up", to: "users#sign_up"
  delete "logout", to: "users#logout"

  post "/graphql", to: "graphql#execute"

  # 搜索和通知
  get "/search" => "search#index", :as => "search"
  get "notifications/index" => "notifications#index"
  delete "notifications/clean" => "notifications#clean"

  resources :users do
    member do
      patch :change_password
      get :articles
      get :comments
      get :favorites
      get :followers
      get :following
      post :follow
      post :unfollow
    end
  end

  get "articles/node:id" => "articles#node", :as => "node_articles"
  resources :articles do
    member do
      post :like
      delete :destroy_like
      post :favorite
      delete :destroy_favorite
    end
    collection do
      get :no_comment
      get :popular
    end
    resources :comments do
      post :like
      delete :destroy_like
    end
  end

  resources :chats

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  # 管理员后台
  namespace :admin do
    # sidekiq后台
    require "sidekiq/web"
    require "sidekiq-status/web"
    require "sidekiq/grouping/web"
    require "sidekiq-scheduler/web"
    mount Sidekiq::Web => "/sidekiq"

    root to: "home#index", as: "root"
    resources :sections
    resources :nodes
    get "foods/new_simple", to: "foods#new_simple"
    resources :foods
    get "practices/bootstrap_table" => "practices#bootstrap_table"
    get "practices/get_data" => "practices#get_data"
    resources :articles
  end

  mount ActionCable.server => "/cable"
end

app/models/section.rb
# frozen_string_literal: true

class Section < ApplicationRecord
  has_many :nodes

  validates_presence_of :name, :sort
end

app/controllers/admin/sections_controller.rb
# frozen_string_literal: true

module Admin
  class SectionsController < Admin::ApplicationController
    def index
      @sections = Section.all
    end

    def new
      @section = Section.new
    end

    def create
      @section = Section.new(permit_params)

      if @section.save
        redirect_to(admin_sections_path, notice: "Section was successfully created.")
      else
        render action: "new"
      end
    end

    def destroy
      @section = Section.find(params[:id])
      @section.destroy

      redirect_to(admin_sections_path, notice: "Section was successfully deleted.")
    end

    def show
    end

    def edit
      @section = Section.find(params[:id])
    end

    def update
      @section = Section.find(params[:id])

      if @section.update_attributes(permit_params)
        redirect_to(admin_sections_path, notice: "Post was successfully updated.")
      else
        render action: "edit"
      end
    end

    private

    def permit_params
      params.require(:section).permit!
    end
  end
end

app/views/admin/sections/edit.html.erb
<section class="content-header">
  <h1>
    Sections
  </h1>
</section>

<section class="content">
  <div class="box box-default">
    <div class="box-header with-border">
      <h3 class="box-title">编辑</h3>
      <%= render 'shared/box_tools' %>
    </div>
    <div class="box-body">
      <%= bootstrap_form_for([:admin,@section], :validate=>true, :html=>{:class=>"form-horizontal"}) do |f| %>
        <%= render 'shared/error_messages', target: @section %>
        <%= f.text_field :name, :class=>'form-control' %>
        <%= f.text_field :sort, :class=>'form-control' %>
        <%= f.submit t('helpers.submit.submit'),:class=>'btn btn-block bg-maroon' %>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/sections/index.html.erb
<section class="content-header">
  <h1>
    Sections
  </h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">
            <%= link_to t('helpers.submit.create'), new_admin_section_path%>
          </h3>
        </div>
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>名称</th>
              <th>排序</th>
              <th>创建时间</th>
              <th>操作</th>
            </tr>
            <tbody>
            <% @sections.each do |section| %>
                <tr>
                  <td><%= section.name %></td>
                  <td><%= section.sort %></td>
                  <td><%= section.created_at.to_date %></td>
                  <td>
                    <%= link_to t('helpers.submit.edit'), edit_admin_section_path(section), :class => 'btn btn-sm btn-warning' %>
                    <%= link_to t('helpers.submit.destroy'), admin_section_path(section), 'data-confirm' => 'Are you sure?',:method => 'delete', :class => 'btn btn-sm btn-danger' %>
                  </td>
                </tr>
            <% end %>
            </table>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/sections/new.html.erb
<section class="content-header">
  <h1>
    Sections
  </h1>
</section>

<section class="content">
  <div class="box box-default">
    <div class="box-header with-border">
      <h3 class="box-title">新建</h3>
      <%= render 'shared/box_tools' %>
    </div>
    <div class="box-body">
      <%= bootstrap_form_for([:admin,@section], :validate=>true, :html=>{:class=>"form-horizontal"}) do |f| %>
          <%= render 'shared/error_messages', target: @section %>
          <%= f.text_field :name, :class=>'form-control' %>
          <%= f.text_field :sort, :class=>'form-control' %>
          <%= f.submit t('helpers.submit.submit'),:class=>'btn btn-block bg-maroon' %>
      <% end %>
    </div>
  </div>
</section>