config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "/language/:locale", to: "users#language", as: :change_locale
  get "register", to: "users#register"
  get "login", to: "users#login"
  post "sign_up", to: "users#sign_up"
  delete "logout", to: "users#logout"

  post "/graphql", to: "graphql#execute"

  # 搜索和通知
  get "/search" => "search#index", :as => "search"
  get "notifications/index" => "notifications#index"
  delete "notifications/clean" => "notifications#clean"

  resources :users do
    member do
      patch :change_password
      get :articles
      get :comments
      get :favorites
      get :followers
      get :following
      post :follow
      post :unfollow
    end
  end

  get "articles/node:id" => "articles#node", :as => "node_articles"
  resources :articles do
    member do
      post :like
      delete :destroy_like
      post :favorite
      delete :destroy_favorite
    end
    collection do
      get :no_comment
      get :popular
    end
    resources :comments do
      post :like
      delete :destroy_like
    end
  end

  resources :chats

  namespace :api do
    namespace :v1 do
      resources :users
    end
  end

  # 管理员后台
  namespace :admin do
    # sidekiq后台
    require "sidekiq/web"
    require "sidekiq-status/web"
    require "sidekiq/grouping/web"
    require "sidekiq-scheduler/web"
    mount Sidekiq::Web => "/sidekiq"

    root to: "home#index", as: "root"
    resources :sections
    resources :nodes
    get "foods/new_simple", to: "foods#new_simple"
    resources :foods
    get "practices/bootstrap_table" => "practices#bootstrap_table"
    get "practices/get_data" => "practices#get_data"
    resources :articles
  end

  mount ActionCable.server => "/cable"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  attr_accessor :new_password, :confirm_password

  mount_uploader :avatar, AvatarUploader
  has_secure_password

  ALLOW_LOGIN_CHARS_REGEXP = /\A[A-Za-z0-9\-_.]+\z/
  validates :full_name, format: {with: ALLOW_LOGIN_CHARS_REGEXP, message: "只允许数字、大小写字母、中横线、下划线"},
                        presence: true,
                        uniqueness: true

  validates :email, email: true,
                    presence: true,
                    uniqueness: true

  validates :item, acceptance: true

  before_create do
    self.auth_token = generate_token
    self.avatar_name = full_name
  end

  def generate_token
    SecureRandom.urlsafe_base64
  end

  def letter_avatar_url(size)
    letter_avatar_address = LetterAvatar.generate(full_name, size)
    avatar_address = Rails.root + letter_avatar_address
    File.open(avatar_address)
  end

  # letter avatar 生成默认头像
  def large_avatar_url
    letter_avatar_url(240)
  end

  def github_url
    return "" if github.blank?

    "https://github.com/#{github.split("/").last}"
  end

  def twitter_url
    return "" if twitter.blank?

    "https://twitter.com/#{twitter}"
  end

  def github_repositories
    cache_key = github_repositories_cache_key
    items = $file_store.read(cache_key)
    if items.nil?
      FetchGithubRepoWorker.perform_async(id)
      items = []
    end
    items
  end

  def github_repositories_cache_key
    "github-repos:#{github}:1"
  end

  def github_repo_api_url
    github_login = github
    resource_name = "users"
    "https://api.github.com/#{resource_name}/#{github_login}/repos?type=owner&sort=pushed&client_id=#{Setting.github_token}&client_secret=#{Setting.github_secret}"
  end

  # 获取github项目列表并存入文件缓存
  def self.fetch_github_repositories(user_id)
    user = User.find_by_id(user_id)
    return unless user

    url = user.github_repo_api_url
    begin
      json = Timeout.timeout(10) { open(url).read }
    rescue => e
      Rails.logger.error("GitHub Repositiory fetch Error: #{e}")
      return false
    end

    items = JSON.parse(json)
    items = items.collect do |a1|
      {
        name: a1["name"],
        url: a1["html_url"],
        watchers: a1["watchers"],
        language: a1["language"],
        description: a1["description"]
      }
    end
    items = items.sort { |a, b| b[:watchers] <=> a[:watchers] }.take(10)
    $file_store.write(user.github_repositories_cache_key, items, expires_in: 15.days)
    items
  end

  # 喜欢文章
  def favorite_article(article_id)
    favorite_article_ids << article_id
    save
  end

  # 取消喜欢文章
  def unfavorite_article(article_id)
    favorite_article_ids.delete(article_id)
    save
  end

  def followed?(user)
    following_ids.include?(user.id)
  end

  # follow用户
  def follow_user(user)
    following_ids << user.id
    self.following_ids = following_ids.uniq
    save
    user.follower_ids << id
    user.follower_ids = user.follower_ids.uniq
    user.save
    Notification.notify_follow(user.id, id)
  end

  # 取消follow用户
  def unfollow_user(user)
    following_ids.delete(user.id)
    save
    user.follower_ids.delete(id)
    user.save
  end

  def following
    User.where(id: following_ids)
  end

  def followers
    User.where(id: follower_ids)
  end

  def read_article(article, opts = {})
    return if article.blank?

    # pluck: select id form comments
    opts[:comment_ids] ||= article.comment.pluck(:id)

    range_sql = "
      (target_type = 'Topic' AND target_id = ?) or
      (target_type = 'Reply' AND target_id in (?))
    "
    notifications.where(range_sql, article.id, opts[:comment_ids]).destroy_all
  end

  def admin?
    Setting.admin_emails.include?(email)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, except: [:register, :create, :login, :sign_up, :logout, :language]

  def register
    @user = User.new
    render layout: false
  end

  def create
    @user = User.new(user_params)
    @user.avatar = @user.large_avatar_url
    if @user.save
      UserMailer.welcome_email(@user).deliver_later
      cookies.permanent[:auth_token] = @user.auth_token
      redirect_to :root
    else
      render :register, layout: false
    end
  end

  def login
    if current_user
      redirect_to root_url
    else
      render layout: false
    end
  end

  def sign_up
    user = User.find_by_email(params[:email])
    if user && user&.authenticate(params[:password])
      user.auth_token = user.generate_token
      user.save
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      flash.notice = "登录成功！"
      redirect_to :root
    else
      flash.alert = "用户名或密码错误！"
      redirect_to :login
    end
  end

  def logout
    cookies.delete(:auth_token)
    flash.notice = "退出登录！"
    redirect_to :root
  end

  def show
    fresh_when([@user])
  end

  def edit
    if @user != current_user
      render_403
    end
  end

  def update
    @user.avatar_name = params[:user][:avatar].try(:original_filename)
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    redirect_to root_url, alert: "软删除，还是物理删除呢?"
  end

  def change_password
    user = params[:user]
    if @user.authenticate(user[:password]) && user[:new_password] == user[:confirm_password]
      # 更新密码操作
      @user.update(password_digest: BCrypt::Password.create(user[:new_password]))
      @user.save
      redirect_to @user, notice: "User was successfully updated."
    else
      @user.errors.add(:password, :invalid)
      render action: "edit"
    end
  end

  # 忘记密码
  # def forget_password
  #   1.点击忘记密码，跳转页面填写邮箱，提交
  #   2.判断邮箱，生成token，邮箱和token作为参数传入链接
  #   3.打开链接，验证email和token，成功进入设置新密码页面，失败提示对应错误信息
  # end

  # 切换语言
  def language
    locale = params[:locale].to_s.strip.to_sym
    cookies[:locale] = locale
    if request.env["HTTP_REFERER"].present?
      redirect_back(fallback_location: request.headers["HTTP_REFERER"])
    else
      redirect_to :root
    end
  end

  # 用户文章
  def articles
    @articles = @user.articles.time_desc.page(params[:page]).per(10)
    fresh_when([@articles, @user])
  end

  def comments
    @comments = @user.comments.time_desc.page(params[:page]).per(10)
    fresh_when([@comments, @user])
  end

  def favorites
    @article_ids = @user.favorite_article_ids
    @articles = Article.where(id: @article_ids).page(params[:page]).per(40)
    fresh_when([@articles])
  end

  def following
    @users = @user.following.page(params[:page]).per(60)
    render template: "/users/followers"
  end

  def followers
    @users = @user.followers.page(params[:page]).per(60)
    fresh_when([@users])
  end

  def follow
    current_user.follow_user(@user)
    render json: {code: 0, data: {followers_count: @user.follower_ids.length}}
  end

  def unfollow
    current_user.unfollow_user(@user)
    render json: {code: 0, data: {followers_count: @user.follower_ids.length}}
  end

  private

  def user_params
    params.require(:user).permit!
  end

  def set_user
    @user = User.find_by_id(params[:id])

    if @user.blank?
      render_404
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # 查看用户连接
  def user_name_tag(user)
    return "匿名" if user.blank?
    name = user.full_name
    link_to(name, user_path(user))
  end

  # 用户头像链接,user:用户,img_class:class,opts:选项
  def user_avatar_tag(user, img_class, opts = {})
    return nil unless user
    image_url = user.avatar.url
    image = image_tag(image_url, class: img_class)

    if opts[:link] != false
      link_to(raw(image), user_path(user))
    else
      raw image
    end
  end

  # 聊天头像
  def chat_avatar_tag(user, img_class)
    return nil unless user
    image_url = user.avatar.url
    image = image_tag(image_url, class: img_class)
    link_to(raw(image), chat_path(user))
  end

  # 是否follow了这个用户
  def follow_user_tag(user, opts = {})
    return "" if current_user.blank?
    return "" if user.blank?
    return "" if current_user.id == user.id
    followed = current_user.followed?(user)
    opts[:class] ||= "btn btn-primary btn-block"
    class_names = "button-follow-user #{opts[:class]}"
    icon = '<i class="fa fa-user"></i>'
    login = user.id
    if followed
      link_to raw("#{icon} <span>取消关注</span>"), "#", "data-id" => login, :class => "#{class_names} active"
    else
      link_to raw("#{icon} <span>关注</span>"), "#", "data-id" => login, :class => class_names
    end
  end
end

app/views/users/_article.html.erb
<table class="node-topics table">
  <tr class="head">
    <td class="node"><%=t("common.node")%></td>
    <td class="title"><%=t("common.title")%></td>
    <td class="replies"><%=t("common.replies_count")%>/<%= t("common.likes_count") %></td>
  </tr>
  <% topics.each do |topic| %>
    <tr class="topic <%= cycle("odd","") %> <%= 'deleted' if topic.deleted? %>">
      <td class="node"><%= render_node_name(topic.node_name,topic.node_id) %></td>
      <td class="title"><%= link_to(topic.title, topic_path(topic)) %> <%= topic_excellent_tag(topic) %> <em><%= timeago(topic.created_at) %></td>
      <td class="replies"><%= topic.replies_count %>/<%= topic.likes_count %> </td>
    </tr>
  <% end %>
</table>

app/views/users/_articles.html.erb
<table class="node-topics table">
  <tr class="head">
    <td class="node"><%= t("common.node") %></td>
    <td class="title"><%= t("common.title") %></td>
    <td class="replies"><%= t("common.replies_count") %>/<%= t("common.likes_count") %></td>
  </tr>
  <% topics.each do |topic| %>
    <tr class="topic <%= cycle("odd", "") %> <%= 'deleted' if topic.deleted? %>">
      <td class="node"><%= render_node_name(topic.node_name, topic.node_id) %></td>
      <td class="title"><%= link_to(topic.title, topic_path(topic)) %> <%= topic_excellent_tag(topic) %>
        <em><%= timeago(topic.created_at) %></td>
      <td class="replies"><%= topic.replies_count %>/<%= topic.likes_count %> </td>
    </tr>
  <% end %>
</table>

app/views/users/_menu.html.erb
<%= render_list class: 'nav nav-tabs' do |li|
  li << link_to('用户信息', user_path(@user))
  li << link_to('文章', articles_user_path(@user))
  li << link_to('回复', comments_user_path(@user))
  li << link_to('收藏', favorites_user_path(@user))
  li << link_to('正在关注', following_user_path(@user))
  li << link_to('关注者', followers_user_path(@user))
end %>

app/views/users/_repos.html.erb
<div class="panel panel-default" id="user_github_repos">
  <% if not user.github.blank? %>
    <div class="panel-heading">GitHub Public Repos</div>
    <ul class="list-group">
      <% user.github_repositories.each do |item| %>
        <li class="list-group-item">
          <div class="title">
            <%= link_to truncate(item[:name], length: 25), item[:url], target: "_blank", rel: "nofollow" %>
            <span class="watchers" title="<%= item[:watchers] %> Watchers"><%= item[:watchers] %></span>
          </div>
          <p class="desc">
            <%= truncate(item[:description], length: 100) %>
        </li>
      <% end %>
    </ul>
    <div class="panel-footer more">
      <%= link_to "More on GitHub", user.github_url, target: "_blank", rel: "nofollow" %>
    </div>
  <% else %>
    <div class="panel-body">
      未设置 GitHub 信息.
    </div>
  <% end %>
</div>

app/views/users/_user_list.html.erb
<%
   columns = 3 if columns == nil
   bs_col = 12 / columns
%>
<% users.each_slice(columns) do |sub_users| %>
  <div class="row">
    <% sub_users.each do |user| %>
      <div class="col-xs-<%= bs_col %>" style="min-width: 100px;">
        <div class="media user-card">
          <div class="media-left"><%= 123 %></div>
          <div class="media-body">
            <div class="media-heading"><%= 123 %></div>
            <div class="infos">
              <div class="item opts"><%= 123 %></div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/articles.html.erb
<div class="row">
  <%= render 'sidebar', user: @user %>
  <div class="col-md-8">
    <%= render 'menu' %>

    <div class="panel panel-default">
      <div class="panel-body">
        <table class="node-topics table table-hover">
          <tr class="head">
            <td class="node">Node</td>
            <td class="title">title</td>
            <td class="replies">comment</td>
          </tr>
          <% @articles.each do |article| %>
            <tr class="topic <%= cycle("odd", "") %>">
              <td class="node_name"><%= link_to(article.node.name, node_articles_path(article.node)) %></td>
              <td class="title_name"><%= link_to(article.title, article_path(article)) %>&nbsp;<em><%= time_ago_now(article.created_at) %></td>
              <td class="replies"><%= article.comments.count %></td>
            </tr>
          <% end %>
        </table>

      </div>
      <div class="box-footer clearfix" id="paginator">
        <!-- kaminari的bootstrap主题-->
        <%= paginate @articles, :theme => 'bootstrap3' %>
      </div>
    </div>
  </div>
</div>

app/views/users/comments.html.erb
<div class="row">
  <%= render "sidebar", user: @user %>
  <div class="col-md-8">
    <%= render "menu" %>
    <div class="panel panel-default">
      <%#= render "comments", comments: @comments %>
      <ul class="list-group recent-replies">
        <% @comments.each do |comment| %>
          <li class="list-group-item">
            <div class="title">
              <%= link_to(comment.article.title, article_path(comment.article_id)) %>
              <span class="info">at <%= time_ago_now(comment.created_at) %></span>
            </div>
            <div class="body markdown">
              <%= markdown comment.body %>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="box-footer clearfix" id="paginator">
        <!-- kaminari的bootstrap主题-->
        <%= paginate @comments, :theme => 'bootstrap3' %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading hide-ios">个人资料设置</div>
      <div class="panel-body">
        <%= form_for @user, :html => {:class => ""} do |f| %>
          <div class="form-group">
            <%= f.label t('users.full_name') %>
            <%= f.text_field :full_name, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label t('users.email') %>
            <%= f.email_field :email, :class => 'form-control', :disabled => true %>
          </div>
          <div class="form-group">
            <%= f.label t('users.avatar') %>
            <%= f.file_field :avatar %>
          </div>
          <div class="form-group">
            <%= f.label t('users.city') %>
            <%= f.text_field :city, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label t('users.company') %>
            <%= f.text_field :company, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label t('users.github') %>
            <div class="input-group">
              <span class="input-group-addon">https://github.com/</span>
              <%= f.text_field :github, :class => 'form-control', :placeholder => '帐号' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label t('users.twitter') %>
            <div class="input-group">
              <span class="input-group-addon">https://twitter.com/</span>
              <%= f.text_field :twitter, :class => 'form-control', :placeholder => '帐号' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label '签名' %>
            <%= f.text_field :tagline, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label t('users.language') %>
            <%= f.select :language, [['简体中文', 'zh-CN'], ['English', 'en']], {}, :class => 'form-control select2' %>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">更新资料</button>
          </div>
        <% end %>
      </div>
    </div>
    <div class="panel panel-default hide-ios">
      <div class="panel-heading">修改密码</div>
      <div class="panel-body">
        <%= form_for(@user, url: change_password_user_path) do |f| %>
          <%= render 'shared/error_messages', target: @user %>
          <div class="form-group">
            <%= f.label '旧密码' %>
            <%= f.password_field :password, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label '密码' %>
            <%= f.password_field :new_password, {:class => 'form-control'} %>
          </div>
          <div class="form-group">
            <%= f.label '确认密码' %>
            <%= f.password_field :confirm_password, {:class => 'form-control'} %>
          </div>
          <div class="form-group">
            <%= f.submit '更新密码', class: 'btn btn-success', 'data-disable-with' => '保存中' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="sidebar col-md-3 hide-ios">
    <div class="panel panel-default" style="text-align:center;">
      <div class="panel-body">
        <%= user_avatar_tag(@user, 'avatar-lg', {link: false}) %>
      </div>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading">删除账户</div>
      <div class="panel-body">
        <%= form_for(@user, :url => user_path, :method => :delete) do |f| %>
          <%= render 'shared/error_messages', :target => @user %>
          <div class="form-group">
            <%= f.password_field :password, class: 'form-control', placeholder: '要删除帐号，请输入你的密码' %>
          </div>
          <%= f.submit '确定删除我的账号', :class => 'btn btn-danger btn-sm btn-block', 'data-disable-with' => '提交中' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <%= render 'sidebar', user: @user %>
  <div class="col-md-8">
    <%= render 'menu' %>
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="node-topics table">
          <tr class="head">
            <td class="opts"><%= t("common.node") %></td>
            <td class="title"><%= t("common.title") %></td>
          </tr>
          <% @articles.each do |item| %>
            <% next if item.blank? %>
            <tr class="topic <%= cycle('odd', "") %>">
              <td class="node_name"><%= link_to item.node.name, node_articles_path(item.node_id) %></td>
              <td class="title_name"><%= link_to item.title, article_path(item) %></td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="panel-footer clearfix">
        <%= paginate @articles, :theme => 'bootstrap3' %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <%= render 'sidebar', user: @user %>
  <div class="col-md-8">
    <%= render 'menu' %>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <% @users.each do |user| %>
            <div class="col-xs-6 col-sm-6 col-md-4">
              <div class="media user-card">
                <div class="media-left"><%= image_tag user.avatar.url, :class => 'avatar' %></div>
                <div class="media-body">
                  <div class="media-heading"><%= user_name_tag(user) %></div>
                  <div class="infos">
                    <div class="item opts"><%= follow_user_tag(user, class: "") %></div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="panel-footer clearfix">
      </div>
    </div>
  </div>
</div>

<script>

  $('.button-follow-user').click(function () {
    var btn, user_id, span, followerCounter
    btn = $(this);
    user_id = btn.data("id");
    span = btn.find("span");
    followerCounter = $(".follow-info .followers .counter");

    if (btn.hasClass("active")) {
      $.ajax({
        url: "/users/" + user_id + "/unfollow",
        type: "POST",
        success: function (res) {
          if (res.code === 0) {
            btn.removeClass('active');
            span.text("关注");
            if (<%= @user.id == current_user.id %>) {
              return followerCounter.text(res.data.followers_count);
            };
          };
        }
      });
    } else {
      $.ajax({
        url: "/users/" + user_id + "/follow",
        type: 'POST',
        success: function (res) {
          if (res.code === 0) {
            btn.addClass('active');
            span.text("取消关注");
            if (<%= @user.id == current_user.id %>) {
              return followerCounter.text(res.data.followers_count);
            };
          };
        }
      });
    }
    return false;
  })

</script>

app/views/users/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Personal Practice</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>AdminLte</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>Malzahar</b>
  </div>
  <%= notice_message %>
  <div class="login-box-body">
    <%= form_tag 'sign_up' do %>
      <div class="form-group has-feedback">
        <%= text_field_tag :email, nil, {:class => "form-control", :placeholder => "Email"} %>
        <span class="fa fa-envelope fa-lg form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <%= password_field_tag :password, nil, {:class => "form-control", :placeholder => "Password"} %>
        <span class="fa fa-lock fa-lg form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <%= check_box_tag :remember_me, 1, false %> remember me
      </div>

      <%= submit_tag '登录', :class => 'btn btn-primary btn-block btn-flat' %>
      <a href="register" class="text-center">Register new account</a>
    <% end %>
    <!--<a href="#">I forgot my password</a><br>-->
    <!--<a href="register.html" class="text-center">Register a new membership</a>-->
  </div>
</div>
</body>
</html>

app/views/users/register.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Personal Practice</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>AdminLte</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <b>Malzahar</b>
  </div>
  <%= render 'shared/error_messages', target: @user %>
  <div class="register-box-body">
    <%= form_for @user do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :full_name, {:class => "form-control", :placeholder => "Full name"} %>
        <span class="fa fa-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <%= f.text_field :email, {:class => "form-control", :placeholder => "Email"} %>
        <span class="fa fa-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <%= f.password_field :password, {:class => "form-control", :placeholder => "Password"} %>
        <span class="fa fa-lock form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <%= f.password_field :password_confirmation, {:class => "form-control", :placeholder => "Confirm Password"} %>
        <span class="fa fa-lock form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <%= f.check_box :item %> <a href="#">agree items</a>
      </div>
      <%= f.submit '注册', :class => 'btn btn-primary btn-block btn-flat' %>
      <a href="login" class="text-center">I already have a membership</a>
    <% end %>
  </div>
</div>
</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <%= render "sidebar", user: @user %>
  <div class="col-md-8">
    <%= render "menu" %>
  </div>
</div>